#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_CONFIG_ADMINISTRATION_PAGE          102
#define IDD_CONFIG_SERVER_PAGE                  103
#define IDD_CONFIG_VIDEO_CLASSES_PAGE           104
#define IDD_CONFIG_ACCESS_CONTROL_PAGE          105
#define IDD_CONFIG_PORT_MAPPING_PAGE            106
#define IDD_CONFIG                              107
#define IDD_EDIT_PORT_MAPPING                   108
#define IDD_EDIT_IP_ACESS_CONTROL               109
#define IDD_CHANGE_PASSWORD                     111
#define IDD_OUTGOING_CONN                       113
#define IDI_IDLE                                115
#define IDI_CONNECTED                           117
#define IDI_DISABLED                            119
#define IDD_CONTROL_AUTH                        123
#define IDD_ABOUT_DIALOG                        125
#define IDB_LOGO_BIG                            127
#define IDD_QUERY_RFB_CONNECTION                128
#define IDC_ACCEPT_BUTTON                       1000
#define IDC_SHOW_TVNCONTROL_ICON_CHECKBOX       1000
#define IDC_STATIC_VERSION                      1000
#define IDC_CONFIG_TAB                          1001
#define IDC_IP_ACCESS_CONTROL_LIST              1001
#define IDC_LOG_LEVEL_SPIN                      1001
#define IDC_PASSWORD_EDIT                       1001
#define IDC_RFB_PORT_SPIN                       1001
#define IDC_VIDEO_CLASS_NAMES                   1001
#define IDC_VIEW_ONLY_CHECKBOX                  1001
#define IDC_VISIT_WEB_SITE_BUTTON               1001
#define IDC_ALLOW_LOOPBACK_CONNECTIONS          1002
#define IDC_LOG_FILEPATH_EDIT                   1002
#define IDC_PORT_EDIT                           1002
#define IDC_UNSET_READONLY_PASSWORD_BUTTON      1002
#define IDC_VIDEO_RECOGNITION_INTERVAL          1002
#define IDC_APPLY                               1003
#define IDC_LOG_FOR_ALL_USERS                   1003
#define IDC_ORDER_SUPPORT_BUTTON                1003
#define IDC_UNSET_PRIMARY_PASSWORD_BUTTON       1003
#define IDC_BLOCK_REMOTE_INPUT                  1004
#define IDC_GRAB_TRANSPARENT                    1005
#define IDC_ADD_BUTTON                          1006
#define IDC_USE_CONTROL_AUTH_CHECKBOX           1006
#define IDC_CONTROL_PASSWORD_BUTTON             1007
#define IDC_EDIT_BUTTON                         1007
#define IDC_REMOVE_BUTTON                       1008
#define IDC_UNSET_CONTROL_PASWORD_BUTTON        1008
#define IDC_GEOMETRY_EDIT                       1009
#define IDC_MOVE_UP_BUTTON                      1009
#define IDC_MOVE_DOWN_BUTTON                    1010
#define IDC_ADD_PORT                            1017
#define IDC_EDIT_PORT                           1018
#define IDC_REMOVE_PORT                         1019
#define IDC_BLOCK_LOCAL_INPUT                   1020
#define IDC_MAPPINGS                            1020
#define IDC_LOCAL_INPUT_PRIORITY_TIMEOUT        1021
#define IDC_LOCAL_INPUT_PRIORITY                1022
#define IDC_TIMEOUT                             1025
#define IDC_REFUSE                              1027
#define IDC_ACCEPT                              1028
#define IDC_ACCEPT_RFB_CONNECTIONS              1052
#define IDC_ACCEPT_HTTP_CONNECTIONS             1053
#define IDC_HTTP_PORT                           1054
#define IDC_RFB_PORT                            1055
#define IDC_LOCK_WORKSTATION                    1059
#define IDC_LOGOFF_WORKSTATION                  1060
#define IDC_ENABLE_FILE_TRANSFERS               1061
#define IDC_REMOVE_WALLPAPER                    1062
#define IDC_LOG_LEVEL                           1065
#define IDC_ALLOW_ONLY_LOOPBACK_CONNECTIONS     1067
#define IDC_APPLET_PARAMS_IN_URL                1068
#define IDC_USE_AUTHENTICATION                  1070
#define IDC_ALLOW                               1082
#define IDC_DENY                                1083
#define IDC_QUERY                               1084
#define IDC_PASSWORD                            1086
#define IDC_PASSWORD2                           1087
#define IDC_PRIMARY_PASSWORD                    1089
#define IDC_SHARED_RADIO1                       1090
#define IDC_VIEW_ONLY_PASSWORD                  1090
#define IDC_SHARED_RADIO2                       1091
#define IDC_SHARED_RADIO3                       1092
#define IDC_SHARED_RADIO4                       1094
#define IDC_SHARED_RADIO5                       1095
#define IDC_POLLING_INTERVAL                    1104
#define IDC_HTTP_PORT_SPIN                      1116
#define IDC_POLLING_INTERVAL_SPIN               1118
#define IDC_QUERY_TIMEOUT_SPIN                  1119
#define IDC_INACTIVITY_TIMEOUT_SPIN             1121
#define IDC_VIDEO_RECOGNITION_INTERVAL_SPIN     1123
#define IDC_IP_FOR_CHECK_EDIT                   1125
#define IDC_IP_CHECK_RESULT_LABEL               1126
#define IDC_OPEN_LOG_FOLDER_BUTTON              1128
#define IDC_DO_NOTHING                          1129
#define IDC_FIRST_IP                            1129
#define IDC_LAST_IP                             1130
#define IDS_SET_CONTROL_PASSWORD_NOTIFICATION   40000
#define ID_ABOUT_TIGHTVNC_MENUITEM              40000
#define IDR_TRAYMENU                            40001
#define IDS_CAPTION_BAD_INPUT                   40001
#define ID_CLOSE_CONTROL_INTERFACE              40001
#define IDS_INVALID_LOG_LEVEL                   40002
#define ID_CONFIGURATION                        40002
#define IDS_CONTROL_SERVER_RAISE_EXCEPTION      40003
#define IDS_CONTROL_CONNECTION_LOST             40004
#define ID_OUTGOING_CONN                        40004
#define IDS_SERVER_ALREADY_RUNNING              40005
#define ID_KILLCLIENTS                          40005
#define IDS_MBC_ERROR                           40006
#define ID_SHUTDOWN_SERVICE                     40006
#define IDS_CANNOT_SAVE_CONFIG                  40007
#define IDS_INVALID_PORT_MAPPING_STRING         40008
#define IDS_PORT_RANGE_ERROR                    40009
#define IDS_PORT_ALREADY_IN_USE                 40010
#define IDS_SET_PASSWORD_NOTIFICATION           40011
#define IDS_MBC_TVNSERVER                       40012
#define IDS_MBC_TVNCONTROL                      40013
#define IDS_LOGPATH_UNAVALIABLE                 40014
#define IDS_PASSWORD_IS_EMPTY                   40015
#define IDS_PASSWORDS_NOT_MATCH                 40016
#define IDS_NEW_PASSWORD                        40017
#define IDS_CHANGE_PASSWORD                     40018
#define IDS_SERVER_TAB_CAPTION                  40019
#define IDC_HOSTNAME_COMBO                      40020
#define IDS_ACCESS_CONTROL_TAB_CAPTION          40020
#define IDS_EXTRA_PORTS_TAB_CAPTION             40021
#define IDS_VIDEO_WINDOWS_TAB_CAPTION           40022
#define IDS_ADMINISTRATION_TAB_CAPTION          40023
#define IDS_SERVICE                             40024
#define IDS_SERVER                              40025
#define IDS_OFFLINE_MODE                        40026
#define IDS_SERVER_CONFIG_CAPTION_FORMAT        40027
#define IDS_INVALID_IP_TITLE                    40028
#define IDS_IP_ADDRESS_HINT                     40029
#define IDS_LAST_IP_MUST_BE_MORE_THAN_FIRST     40030
#define IDS_NEW_IP_ACCESS_RULE_DIALOG_CAPTION   40031
#define IDS_EDIT_IP_ACCESS_RULE_DIALOG_CAPTION  40032
#define IDS_QUERY_TIMEOUT_TOO_SMALL             40033
#define IDS_FIRST_IP_COLUMN                     40034
#define IDS_LAST_IP_COLUMN                      40035
#define IDS_ACTION_COLUMN                       40036
#define IDS_SET_PASSWORD_CAPTION                40037
#define IDS_CHANGE_PASSWORD_CAPTION             40038
#define IDS_HTTP_RFB_PORTS_ARE_EQUAL            40039
#define IDS_POLL_INTERVAL_TOO_SMALL             40040
#define IDS_INACTIVITY_TIMEOUT_TOO_SMALL        40041
#define IDS_BAD_IP_HINT                         40042
#define IDS_ACTION_UNDEF_HINT                   40043
#define IDS_ACTION_ACCEPT_HINT                  40044
#define IDS_ACTION_REJECT_HINT                  40045
#define IDS_ACTION_QUERY_HINT                   40046
#define IDS_ACTION_ACCEPT                       40047
#define IDS_ACTION_DENY                         40048
#define IDS_ACTION_QUERY                        40049
#define IDS_USER_CANCEL_CONTROL_AUTH            40050
#define IDS_TVNSERVER_USAGE                     40051
#define IDS_SERVER_NOT_LISTENING                40052
#define IDS_FAILED_TO_CONNECT_TO_CONTROL_SERVER 40053
#define IDS_MBC_TVNSERVER_USAGE                 40054
#define IDS_UNSET_PASSWORD_PROMT                40055
#define IDS_FAILED_TO_OPEN_URL_FORMAT           40056
#define IDS_PRODUCT_VERSION_FORMAT              40057
#define IDS_OFFLINE_CONFIG_SAVE_NOTIFICATION    40058
#define IDS_ADMIN_RIGHTS_NEEDED                 40059
#define IDS_AUTO_ACCEPT_CONNECTION_FORMAT       40060
#define IDS_AUTO_REJECT_CONNECTION_FORMAT       40061
#define IDS_INVALID_CONTROL_PASSWORD            40062
#define IDS_TIGHTVNC_SUPPORT_URL                40063
#define IDS_TIGHTVNC_URL                        40064
#define IDS_SERVICE_STOP_TIMEOUT                40065
#define IDS_SERVICE_START_TIMEOUT               40066
#define IDS_SERVICE_ALREADY_RUNNING             40067
#define IDS_SERVICE_ALREADY_STOPPED             40068
#define IDS_CONTROL_CLIENT_NOT_CONNECTED        40069
#define IDS_FAILED_TO_INSTALL_SERVICE_FORMAT    40070
#define IDS_FAILED_TO_REMOVE_SERVICE_FORMAT     40071
#define IDS_FAILED_TO_START_SERVICE_FORMAT      40072
#define IDS_FAILED_TO_STOP_SERVICE_FORMAT       40073
#define IDS_SERVICE_INSTALLED                   40074
#define IDS_SERVICE_REMOVED                     40075
#define IDS_SERVICE_REINSTALLED                 40076
#define IDC_REJECT_BUTTON                       40077
#define IDS_INVALID_POLLING_INTERVAL            40077
#define IDC_IP_EDIT                             40078
#define IDS_INVALID_INACTIVITY_TIMEOUT          40078
#define IDC_TIMEOUT_LABEL                       40079
#define IDS_NO_PASSWORDS_SET                    40079
#define IDS_INVALID_QUERY_TIMEOUT               40080
#define IDS_INVALID_VIDEO_RECOGNITION_INTERVAL  40081
#define IDS_TVNSERVER_SERVICE                   40082
#define IDS_1060_ERROR_DESCRIPTION              40083
#define IDS_TVNSERVER_APP                       40084
#define IDS_1073_ERROR_DESCRIPTION              40085
#define IDS_SHUTDOWN_NOTIFICATION_FORMAT        40086
#define IDS_NO_AUTH_STATUS                      40087
