#define ID_CONN_CTLESC                  102
#define ID_CONN_ABOUT                   103
#define ID_CONN_CTLDOWN                 104
#define ID_CONN_CTLUP                   105
#define ID_CONN_ALTDOWN                 106
#define ID_CONN_ALTUP                   107
#define ID_CONN_CTLALTDEL               108
#define ID_FULLSCREEN                   110
#define ID_REQUEST_REFRESH              111
#define ID_CONN_SAVE_AS                 153
#define ID_ENABLE_VIDEO_HANDLING        155
#define ID_TOOLBAR                      159
#define ID_SESSION_SET_CRECT            32777
#define ID_SESSION_SWAPMOUSE            32785
#define ID_CLOSEDAEMON                  40001
#define ID_NEWCONN                      40006
#define IDT_EMULATE3BUTTONSTIMER        152
#define IDT_TRAYTIMER                   109
#define IDD_FILETRANSFER                40010
#define IDC_UPLOAD                      1080
#define IDC_DOWNLOAD                    1081
